### ISSUE TITLE
Agregar topic #Hacktoberfest

### ISSUE THREAD

**Issue by ElMachado** [xaca/banderas_java#23]
Para que los PR sean aceptados en Hactoberfest se debe clasificar el repositorio con el tema hacktoberfest y aplicar etiquetas aceptadas por hacktoberfest a las solicitudes de extracción que desea aceptar. 
GIF de referencia. 
![GIF](https://hacktoberfest-assets.nyc3.cdn.digitaloceanspaces.com/hacktoberfest-eligible-gif.gif)

**Comment by xaca** [comment]
@ElMachado Gracias Jesus, no habia visto, super bien el comentario 🥇 💯
